language: php
os:
  - linux

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

services:
  - mysql

env:
  # deploy master to svn truck
  - WP_VERSION=latest WP_MULTISITE=0 DEPLOYMASTER=1
  - WP_VERSION=latest WP_MULTISITE=1
  - WP_VERSION=5.2 WP_MULTISITE=0
  # - WP_VERSION=5.2 WP_MULTISITE=1

before_script:
  - phpenv config-rm xdebug.ini
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer self-update
  - composer install
  - phpenv versions
  - php --version

script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
  - git clone https://github.com/litefeel/deploy2wp.git
  - sh deploy2wp/scripts/install.sh

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

after_success:
  - |
    echo "TRAVIS_PHP_VERSION:$TRAVIS_PHP_VERSION"
    if [[ "$DEPLOYMASTER" == "1" && "$TRAVIS_PHP_VERSION" == "7.4" ]]; then
      deploy2wp/scripts/deploy2wp.sh
    fi
