language: php
os:
  - linux

# deploy master to svn truck
# env: DEPLOYMASTER=1

before_script:
  - git https://github.com/litefeel/deploy2wp.git
  - sh deploy2wp/scripts/install.sh
  - deploy2wp/scripts/wp2md.sh README.md readme.txt to-wp
  - cat readme.txt

script:
  - deploy2wp/scripts/deploy2wp.sh
